version: '3'
services:
    db:
        image: postgres
        environment:
            POSTGRES_DB: user
            POSTGRES_USER: user
            POSTGRES_PASSWORD: user
        ports:
            -   "12345:5432"
        volumes:
            -   ./docker/pgdata:/var/libs/postgresql/data
